s3_bucket:
  train_data: wafer-train-data-5acbd2d
  logs: wafer-logs-4e1f3bd

dir:
  train_good_data: good/train
  log: data_transform_train_logs

log:
  data_transform: train_data_transform.log
  data_transform_main: data_transform_main.log
  upload: upload_data_transform_train.log

col:
  output: Output
  good_bad: Good/Bad

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
