s3_bucket:
  io_files: wafer-io-files-03e0100
  model: wafer-model-3e502a3
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  features: wafer_train_features.csv
  targets: wafer_train_targets.csv
  elbow_plot: K-Means_Elbow_train.png

log:
  clustering: train_clustering.log
  upload: upload_train_cluster.log

dir:
  model_trained: trained
  log: clustering_logs

KMeans:
  init: k-means++
  random_state: 42

max_clusters: 11

model_save_format: .sav

knee:
  curve: convex
  direction: decreasing

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
